language: node_js

node_js:
  - "0.8"
  - "0.10"

before_script:
  - "npm install -g grunt-cli"
  - "npm install -g docco"
  - "npm install"

script:
  - "grunt"

notifications:
  email:
    - ram@hiddentao.com
    - nl.imbecile@gmail.com

